// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: graph/v1/spec.proto

package graph

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Top level message that keeps track of all the vertices and edges
type Graph struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vertices        []*Vertice       `protobuf:"bytes,1,rep,name=vertices,proto3" json:"vertices,omitempty"`
	Edges           []*Edge          `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	Routes          []*Route         `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	AdjacencyMatrix *AdjacencyMatrix `protobuf:"bytes,4,opt,name=adjacencyMatrix,proto3" json:"adjacencyMatrix,omitempty"`
}

func (x *Graph) Reset() {
	*x = Graph{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_v1_spec_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Graph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graph) ProtoMessage() {}

func (x *Graph) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_spec_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graph.ProtoReflect.Descriptor instead.
func (*Graph) Descriptor() ([]byte, []int) {
	return file_graph_v1_spec_proto_rawDescGZIP(), []int{0}
}

func (x *Graph) GetVertices() []*Vertice {
	if x != nil {
		return x.Vertices
	}
	return nil
}

func (x *Graph) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *Graph) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *Graph) GetAdjacencyMatrix() *AdjacencyMatrix {
	if x != nil {
		return x.AdjacencyMatrix
	}
	return nil
}

// Vertice
type Vertice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Label string  `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	X     float32 `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y     float32 `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Vertice) Reset() {
	*x = Vertice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_v1_spec_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vertice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vertice) ProtoMessage() {}

func (x *Vertice) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_spec_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vertice.ProtoReflect.Descriptor instead.
func (*Vertice) Descriptor() ([]byte, []int) {
	return file_graph_v1_spec_proto_rawDescGZIP(), []int{1}
}

func (x *Vertice) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Vertice) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Vertice) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vertice) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Edge
type Edge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source *Vertice `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target *Vertice `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Weight float32  `protobuf:"fixed32,3,opt,name=weight,proto3" json:"weight,omitempty"`
}

func (x *Edge) Reset() {
	*x = Edge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_v1_spec_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_spec_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_graph_v1_spec_proto_rawDescGZIP(), []int{2}
}

func (x *Edge) GetSource() *Vertice {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Edge) GetTarget() *Vertice {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Edge) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

// Route
type Route struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vertice           []*Vertice `protobuf:"bytes,1,rep,name=vertice,proto3" json:"vertice,omitempty"`
	AccumulatedWeight []float32  `protobuf:"fixed32,2,rep,packed,name=accumulatedWeight,proto3" json:"accumulatedWeight,omitempty"`
}

func (x *Route) Reset() {
	*x = Route{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_v1_spec_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_spec_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_graph_v1_spec_proto_rawDescGZIP(), []int{3}
}

func (x *Route) GetVertice() []*Vertice {
	if x != nil {
		return x.Vertice
	}
	return nil
}

func (x *Route) GetAccumulatedWeight() []float32 {
	if x != nil {
		return x.AccumulatedWeight
	}
	return nil
}

// Adjacency Matrix
type AdjacencyMatrix struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row []*Row `protobuf:"bytes,1,rep,name=row,proto3" json:"row,omitempty"`
}

func (x *AdjacencyMatrix) Reset() {
	*x = AdjacencyMatrix{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_v1_spec_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdjacencyMatrix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjacencyMatrix) ProtoMessage() {}

func (x *AdjacencyMatrix) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_spec_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjacencyMatrix.ProtoReflect.Descriptor instead.
func (*AdjacencyMatrix) Descriptor() ([]byte, []int) {
	return file_graph_v1_spec_proto_rawDescGZIP(), []int{4}
}

func (x *AdjacencyMatrix) GetRow() []*Row {
	if x != nil {
		return x.Row
	}
	return nil
}

// Row
type Row struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Weight []float32 `protobuf:"fixed32,1,rep,packed,name=weight,proto3" json:"weight,omitempty"`
}

func (x *Row) Reset() {
	*x = Row{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_v1_spec_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_spec_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_graph_v1_spec_proto_rawDescGZIP(), []int{5}
}

func (x *Row) GetWeight() []float32 {
	if x != nil {
		return x.Weight
	}
	return nil
}

var File_graph_v1_spec_proto protoreflect.FileDescriptor

var file_graph_v1_spec_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67, 0x72, 0x61, 0x70, 0x68, 0x22, 0xbe, 0x01, 0x0a,
	0x05, 0x47, 0x72, 0x61, 0x70, 0x68, 0x12, 0x2a, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x74, 0x69, 0x63,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68,
	0x2e, 0x56, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65, 0x52, 0x08, 0x76, 0x65, 0x72, 0x74, 0x69, 0x63,
	0x65, 0x73, 0x12, 0x21, 0x0a, 0x05, 0x65, 0x64, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x45, 0x64, 0x67, 0x65, 0x52, 0x05,
	0x65, 0x64, 0x67, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x12, 0x40, 0x0a, 0x0f, 0x61,
	0x64, 0x6a, 0x61, 0x63, 0x65, 0x6e, 0x63, 0x79, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x41, 0x64, 0x6a,
	0x61, 0x63, 0x65, 0x6e, 0x63, 0x79, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x52, 0x0f, 0x61, 0x64,
	0x6a, 0x61, 0x63, 0x65, 0x6e, 0x63, 0x79, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x22, 0x4b, 0x0a,
	0x07, 0x56, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x22, 0x6e, 0x0a, 0x04, 0x45, 0x64,
	0x67, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x56, 0x65, 0x72, 0x74, 0x69,
	0x63, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x72, 0x61,
	0x70, 0x68, 0x2e, 0x56, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x5f, 0x0a, 0x05, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x56, 0x65, 0x72,
	0x74, 0x69, 0x63, 0x65, 0x52, 0x07, 0x76, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a,
	0x11, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x57, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x02, 0x52, 0x11, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x75,
	0x6c, 0x61, 0x74, 0x65, 0x64, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x2f, 0x0a, 0x0f, 0x41,
	0x64, 0x6a, 0x61, 0x63, 0x65, 0x6e, 0x63, 0x79, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x12, 0x1c,
	0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x72,
	0x61, 0x70, 0x68, 0x2e, 0x52, 0x6f, 0x77, 0x52, 0x03, 0x72, 0x6f, 0x77, 0x22, 0x1d, 0x0a, 0x03,
	0x52, 0x6f, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x02, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x42, 0x10, 0x5a, 0x0e, 0x63,
	0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_graph_v1_spec_proto_rawDescOnce sync.Once
	file_graph_v1_spec_proto_rawDescData = file_graph_v1_spec_proto_rawDesc
)

func file_graph_v1_spec_proto_rawDescGZIP() []byte {
	file_graph_v1_spec_proto_rawDescOnce.Do(func() {
		file_graph_v1_spec_proto_rawDescData = protoimpl.X.CompressGZIP(file_graph_v1_spec_proto_rawDescData)
	})
	return file_graph_v1_spec_proto_rawDescData
}

var file_graph_v1_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_graph_v1_spec_proto_goTypes = []interface{}{
	(*Graph)(nil),           // 0: graph.Graph
	(*Vertice)(nil),         // 1: graph.Vertice
	(*Edge)(nil),            // 2: graph.Edge
	(*Route)(nil),           // 3: graph.Route
	(*AdjacencyMatrix)(nil), // 4: graph.AdjacencyMatrix
	(*Row)(nil),             // 5: graph.Row
}
var file_graph_v1_spec_proto_depIdxs = []int32{
	1, // 0: graph.Graph.vertices:type_name -> graph.Vertice
	2, // 1: graph.Graph.edges:type_name -> graph.Edge
	3, // 2: graph.Graph.routes:type_name -> graph.Route
	4, // 3: graph.Graph.adjacencyMatrix:type_name -> graph.AdjacencyMatrix
	1, // 4: graph.Edge.source:type_name -> graph.Vertice
	1, // 5: graph.Edge.target:type_name -> graph.Vertice
	1, // 6: graph.Route.vertice:type_name -> graph.Vertice
	5, // 7: graph.AdjacencyMatrix.row:type_name -> graph.Row
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_graph_v1_spec_proto_init() }
func file_graph_v1_spec_proto_init() {
	if File_graph_v1_spec_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_graph_v1_spec_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Graph); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_v1_spec_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vertice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_v1_spec_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Edge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_v1_spec_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Route); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_v1_spec_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdjacencyMatrix); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_v1_spec_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Row); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_graph_v1_spec_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_graph_v1_spec_proto_goTypes,
		DependencyIndexes: file_graph_v1_spec_proto_depIdxs,
		MessageInfos:      file_graph_v1_spec_proto_msgTypes,
	}.Build()
	File_graph_v1_spec_proto = out.File
	file_graph_v1_spec_proto_rawDesc = nil
	file_graph_v1_spec_proto_goTypes = nil
	file_graph_v1_spec_proto_depIdxs = nil
}
