# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graph/v1/spec.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='graph/v1/spec.proto',
  package='graph',
  syntax='proto3',
  serialized_options=b'Z\006.;main',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13graph/v1/spec.proto\x12\x05graph\"\x94\x01\n\x05Graph\x12 \n\x08vertices\x18\x01 \x03(\x0b\x32\x0e.graph.Vertice\x12\x1a\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\x0b.graph.Edge\x12\x1c\n\x06routes\x18\x03 \x03(\x0b\x32\x0c.graph.Route\x12/\n\x0f\x61\x64jacencyMatrix\x18\x04 \x01(\x0b\x32\x16.graph.AdjacencyMatrix\":\n\x07Vertice\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05label\x18\x02 \x01(\t\x12\t\n\x01x\x18\x03 \x01(\x02\x12\t\n\x01y\x18\x04 \x01(\x02\"V\n\x04\x45\x64ge\x12\x1e\n\x06source\x18\x01 \x01(\x0b\x32\x0e.graph.Vertice\x12\x1e\n\x06target\x18\x02 \x01(\x0b\x32\x0e.graph.Vertice\x12\x0e\n\x06weight\x18\x03 \x01(\x02\"C\n\x05Route\x12\x1f\n\x07vertice\x18\x01 \x03(\x0b\x32\x0e.graph.Vertice\x12\x19\n\x11\x61\x63\x63umulatedWeight\x18\x02 \x03(\x02\"*\n\x0f\x41\x64jacencyMatrix\x12\x17\n\x03row\x18\x01 \x03(\x0b\x32\n.graph.Row\"\x15\n\x03Row\x12\x0e\n\x06weight\x18\x01 \x03(\x02\x42\x08Z\x06.;mainb\x06proto3'
)




_GRAPH = _descriptor.Descriptor(
  name='Graph',
  full_name='graph.Graph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vertices', full_name='graph.Graph.vertices', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='edges', full_name='graph.Graph.edges', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='routes', full_name='graph.Graph.routes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='adjacencyMatrix', full_name='graph.Graph.adjacencyMatrix', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=179,
)


_VERTICE = _descriptor.Descriptor(
  name='Vertice',
  full_name='graph.Vertice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='graph.Vertice.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='label', full_name='graph.Vertice.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='graph.Vertice.x', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='graph.Vertice.y', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=239,
)


_EDGE = _descriptor.Descriptor(
  name='Edge',
  full_name='graph.Edge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='graph.Edge.source', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target', full_name='graph.Edge.target', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weight', full_name='graph.Edge.weight', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=327,
)


_ROUTE = _descriptor.Descriptor(
  name='Route',
  full_name='graph.Route',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vertice', full_name='graph.Route.vertice', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accumulatedWeight', full_name='graph.Route.accumulatedWeight', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=396,
)


_ADJACENCYMATRIX = _descriptor.Descriptor(
  name='AdjacencyMatrix',
  full_name='graph.AdjacencyMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='row', full_name='graph.AdjacencyMatrix.row', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=398,
  serialized_end=440,
)


_ROW = _descriptor.Descriptor(
  name='Row',
  full_name='graph.Row',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='weight', full_name='graph.Row.weight', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=442,
  serialized_end=463,
)

_GRAPH.fields_by_name['vertices'].message_type = _VERTICE
_GRAPH.fields_by_name['edges'].message_type = _EDGE
_GRAPH.fields_by_name['routes'].message_type = _ROUTE
_GRAPH.fields_by_name['adjacencyMatrix'].message_type = _ADJACENCYMATRIX
_EDGE.fields_by_name['source'].message_type = _VERTICE
_EDGE.fields_by_name['target'].message_type = _VERTICE
_ROUTE.fields_by_name['vertice'].message_type = _VERTICE
_ADJACENCYMATRIX.fields_by_name['row'].message_type = _ROW
DESCRIPTOR.message_types_by_name['Graph'] = _GRAPH
DESCRIPTOR.message_types_by_name['Vertice'] = _VERTICE
DESCRIPTOR.message_types_by_name['Edge'] = _EDGE
DESCRIPTOR.message_types_by_name['Route'] = _ROUTE
DESCRIPTOR.message_types_by_name['AdjacencyMatrix'] = _ADJACENCYMATRIX
DESCRIPTOR.message_types_by_name['Row'] = _ROW
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Graph = _reflection.GeneratedProtocolMessageType('Graph', (_message.Message,), {
  'DESCRIPTOR' : _GRAPH,
  '__module__' : 'graph.v1.spec_pb2'
  # @@protoc_insertion_point(class_scope:graph.Graph)
  })
_sym_db.RegisterMessage(Graph)

Vertice = _reflection.GeneratedProtocolMessageType('Vertice', (_message.Message,), {
  'DESCRIPTOR' : _VERTICE,
  '__module__' : 'graph.v1.spec_pb2'
  # @@protoc_insertion_point(class_scope:graph.Vertice)
  })
_sym_db.RegisterMessage(Vertice)

Edge = _reflection.GeneratedProtocolMessageType('Edge', (_message.Message,), {
  'DESCRIPTOR' : _EDGE,
  '__module__' : 'graph.v1.spec_pb2'
  # @@protoc_insertion_point(class_scope:graph.Edge)
  })
_sym_db.RegisterMessage(Edge)

Route = _reflection.GeneratedProtocolMessageType('Route', (_message.Message,), {
  'DESCRIPTOR' : _ROUTE,
  '__module__' : 'graph.v1.spec_pb2'
  # @@protoc_insertion_point(class_scope:graph.Route)
  })
_sym_db.RegisterMessage(Route)

AdjacencyMatrix = _reflection.GeneratedProtocolMessageType('AdjacencyMatrix', (_message.Message,), {
  'DESCRIPTOR' : _ADJACENCYMATRIX,
  '__module__' : 'graph.v1.spec_pb2'
  # @@protoc_insertion_point(class_scope:graph.AdjacencyMatrix)
  })
_sym_db.RegisterMessage(AdjacencyMatrix)

Row = _reflection.GeneratedProtocolMessageType('Row', (_message.Message,), {
  'DESCRIPTOR' : _ROW,
  '__module__' : 'graph.v1.spec_pb2'
  # @@protoc_insertion_point(class_scope:graph.Row)
  })
_sym_db.RegisterMessage(Row)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
